# This is a basic workflow to help you get started with Actions

name: Build and Release

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Rust minimal stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-i686-pc-windows-msvc
          profile: minimal
          target: i686-pc-windows-msvc
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target i686-pc-windows-msvc --release
          
      - name: Download VICE 3.5
        # You may pin to the exact commit or the version.
        # uses: carlosperate/download-file-action@e85e0aa6262f13571d17a4a39687b26981c583dc
        uses: carlosperate/download-file-action@v1.0.3
        with:
          # URL of the file to download
          file-url: 'https://csdb.dk/release/download.php?id=245174'
          file-name: GTK3VICE-3.5-win32.7z
        
          
      - name: Extract VICE 3.5
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          # archive path to extract
          pathSource: GTK3VICE-3.5-win32.7z
          # path to place the extract
          pathTarget: $GITHUB_WORKSPACE/assets
          
      - run: tree \
          
